#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
elif [[ $WSL_DISTRO_NAME ]]; then
  export BROWSER='wslview'
fi

#
# Editors
#

export EDITOR='emacs'
export VISUAL='emacs'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi


export PATH="$HOME/.cargo/bin:$PATH"

eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

# for X
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export DefaultIMModule=fcitx

# if X11 server available, start fcixt.
if test "$SHLVL" -eq 1 && nc -v "$(echo "$DISPLAY" | cut -d : -f 1)" 6000 -w 1 > /dev/null 2>&1; then
   fcitx-remote > /dev/null 2>&1
   if [ $? = "1" ]; then
       fcitx-autostart > /dev/null 2>&1
   fi
else
    echo "X11 server not stated"
:
fi
