#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
   source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

for c in wslfetch wslpath wslsys wslupath wslusc wslvar wslview
do
	alias $c="PATH=\"$PATH:/mnt/c/windows/system32\" $c"
done


eval "$(direnv hook zsh)"

zstyle ':prezto:load' pmodule-dirs $HOME/.zsh-contrib

if (which zprof > /dev/null 2>&1) ;then
   zprof | less
fi

fpath=(~/.zsh-contrib/cd-bookmark(N-/) $fpath)
autoload -Uz cd-bookmark

autoload -U +X bashcompinit && bashcompinit
source ~/.zsh-contrib/az.completion

alias open=wslview
alias cdb='cd-bookmark'


#

function cdw {
    cd `wslpath "$1"`
}
